/** Anbieterdaten für Rechnungen (entspricht bc-charge.de / Impressum). */
export const companyInfo = {
  legalName: 'Byte Commander GmbH',
  legalForm: 'GmbH',
  brand: 'BC Charge',
  street: 'Grüner Weg 3',
  zip: '04827',
  city: 'Machern',
  country: 'Deutschland',
  phone: '+49 (0) 34292 43340',
  phoneTel: '+493429243340',
  email: process.env.BC_INVOICE_EMAIL ?? 'hello@bc-charge.com',
  emailInvoice: process.env.BC_INVOICE_COPY_EMAIL ?? 'invoice@bc-charge.com',
  website: 'https://bc-charge.de',
  websiteDisplay: 'bc-charge.de',
  managingDirector: 'Matthias Schmitz',
  registerCourt: 'Amtsgericht Leipzig',
  registerNumber: 'HRB 38559',
  vatId: process.env.BC_VAT_ID ?? 'DE343089057',
  taxNumber: process.env.BC_TAX_NUMBER ?? null,
};
